config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => "/cable"

  root "rooms#index"

  resources :rooms, only: [:create, :show], param: :uuid
  resources :authentications, only: [:create], param: :uuid
  get "authenticate/:room_uuid", to: "authentications#index", as: "authenticate"

  resources :messages, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  encrypts :username, type: :string
  encrypts :room_uuid, type: :string
  encrypts :token, type: :string

  blind_index :token, slow: true
end

app/models/room.rb
class Room < ApplicationRecord
  has_secure_password validations: false

  encrypts :name, type: :string
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
    @authentication = Authentication.new
  end

  def create
    @authentication = Authentication.new
    @authentication.username = authentication_params[:username]
    @authentication.room_uuid = authentication_params[:room_uuid]
    @authentication.uuid = SecureRandom.uuid

    room_uuid = authentication_params[:room_uuid]
    @room = Room.find_by_uuid(room_uuid)

    if @room
      if @room.password_digest
        unless @room.authenticate(authentication_params[:password])
          send_failed_login_broadcast
          redirect_to authenticate_path(room_uuid)
          return
        end
      end

      generate_authentication_token

      if @authentication.save
        set_authentication_cookie
        redirect_to room_path(room_uuid)
      else
        send_failed_login_broadcast
        redirect_to authenticate_path(room_uuid)
      end
    end
  end

  private

  def send_failed_login_broadcast
    ChatChannel.broadcast_to @room,
      type: "server",
      uuid: @room.uuid,
      content: "Someone attempted to join the room but failed.",
      timestamp: Time.now
  end

  def generate_authentication_token
    @authentication.token = SecureRandom.base64
  end

  def set_authentication_cookie
    cookies.encrypted[:authentication_token] = @authentication.token
  end

  def authentication_params
    params.require(:authentication).permit(:username, :password, :room_uuid)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    return if message_params[:content].empty?

    @room = Room.find_by_uuid(message_params[:room_uuid])
    @token = Authentication.find_by_token(cookies.encrypted[:authentication_token])
    username = @token.username

    set_user_color

    ChatChannel.broadcast_to @room,
      uuid: message_params[:room_uuid],
      content: message_params[:content],
      username: username,
      color: @color,
      timestamp: Time.now
  end

  private

  def set_user_color
    srand(@token.id)
    @color = "hsl(#{rand() * 360}, #{55 + (70 * rand())}%, #{50 + (10 * rand())}%)"
  end

  def message_params
    params.require(:message).permit(:content, :room_uuid)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :does_room_exist, :authenticate]
  before_action :does_room_exist, only: [:show]
  before_action :authenticate, only: [:show]
  before_action :set_room_cookie, only: [:show]

  def index
    @room = Room.new
  end

  def show
    @username = Authentication.find_by_token(cookies.encrypted[:authentication_token]).username
  end

  def create
    @room = Room.new(room_params)
    @room.uuid = SecureRandom.uuid

    if @room.save
      redirect_to room_path(@room.uuid)
    else
      redirect_to root_path
    end
  end

  private

  def set_room
    @room = Room.find_by_uuid(params[:uuid])
  end

  def set_room_cookie
    cookies.encrypted[:room_uuid] = params[:uuid]
  end

  def room_params
    params.require(:room).permit(:name, :password, :password_confirmation, :expiration_time)
  end

  def authenticate
    token = Authentication.find_by_token(cookies.encrypted[:authentication_token])

    if token.nil? || @room.nil? || token.room_uuid != @room.uuid
      redirect_to authenticate_path(params[:uuid])
    end
  end

  def does_room_exist
    unless @room.present?
      redirect_to authenticate_path(params[:uuid])
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def inline_file(path)
    if assets = Rails.application.assets
      asset = assets.find_asset(path)
      return "" unless asset
      asset.source
    else
      File.read(File.join(Rails.root, "public", asset_path(path)))
    end
  end
  
  def inline_js(path)
    "<script>#{ inline_file path }</script>".html_safe
  end

  def inline_css(path)
    "<style>#{ inline_file path }</style>".html_safe
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/authentications/index.html.erb
<%= params[:room_uuid] %>

<%= form_for @authentication do |form| %>
  <%= form.hidden_field :room_uuid, value: params[:room_uuid] %>
  <%= form.text_field :username, placeholder: "Username", class: "form-input" %>
  <%= form.password_field :password, placeholder: "Room Password", class: "form-input" %>

  <%= button_tag "Submit", class: "button button--primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EncryptedChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= inline_css "application.css" %>
  </head>

  <body>
    <main class="wrapper">
      <%= yield %>
    </main>

    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/index.html.erb
abc

app/views/rooms/_chat_item.html.erb
<template id="chat-item">
  <div part="username"></div>

  <div part="content">
    <slot></slot>
  </div>

  <div part="timestamp"></div>
  <div part="timer"></div>
</template>

app/views/rooms/index.html.erb
<%= form_for @room do |form| %>
  <p>
    <%= form.text_field :name, placeholder: "Room name (optional)", class: "form-input" %>
  </p>

  <%= form.password_field :password, placeholder: "Password (optional)", class: "form-input" %>
  <%= form.password_field :password_confirmation, placeholder: "Password confirmation", class: "form-input" %>

  <p>
    <%= form.text_field :expiration_time, placeholder: "Message expiration time (in seconds)", value: "", class: "form-input" %>
  </p>

  <%= button_tag "Submit", class: "button button--primary" %>
<% end %>

app/views/rooms/show.html.erb
<%= render "chat_item" %>

<div class="app">
  <div class="header" data-uuid="<%= @room.uuid %>">
    <%= @room.uuid %> <br>
    <%= @username %> <br>
    <% if @room.expiration_time %>
      <small>Expiration time: <%= @room.expiration_time %> seconds</small>
    <% end %>
  </div>

  <div class="chat-container" data-role="chat-container" data-expiration="<%= @room.expiration_time %>" data-username="<%= @username %>"></div>

  <div class="drawer">
    <%= form_for :message, url: messages_path, method: :post, remote: true, data: { role: "chat-message" } do |form| %>
      <div class="form-group">
        <%= form.text_area :content, placeholder: "Type a message...", class: "form-input", autocomplete: "off", rows: 2 %>
        <%= form.hidden_field :room_uuid, value: @room.uuid %>

        <%= button_tag "➤", class: "submit" %>
      </div>
    <% end %>
  </div>
</div>